# Generated by Django 2.0.2 on 2018-02-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180202_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_pref',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10, verbose_name='How should we contact you?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_time_pref',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='evening', max_length=20, verbose_name='When should we contact you?'),
        ),
    ]
